// Reads everything under /content (edited via the Decap CMS admin panel, or by hand)
// and turns it into the TypeScript data files the React app imports.
// Runs automatically before every `npm run dev` and `npm run build` (see package.json).
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import matter from 'gray-matter'
import yaml from 'js-yaml'
import { validateContent } from './validate-content.mjs'
import { normalizeVisualBlocks } from './normalize-visual-blocks.mjs'

const root = path.resolve(import.meta.dirname, '..')
const contentDir = path.join(root, 'content')
const outDir = path.join(root, 'src', 'data', 'generated')

validateContent(root)
mkdirSync(outDir, { recursive: true })

function readMarkdownFolder(folder) {
  const dir = path.join(contentDir, folder)
  let files = []
  try {
    files = readdirSync(dir).filter((f) => f.endsWith('.md'))
  } catch {
    return []
  }
  return files.map((file) => {
    const raw = readFileSync(path.join(dir, file), 'utf8')
    const { data, content } = matter(raw)
    const id = file.replace(/\.md$/, '')
    return { id, ...data, body: content.trim() }
  })
}

function jsonString(value) {
  return JSON.stringify(value, null, 2)
}

// --- subjects.yml (levels + subjects) --------------------------------
const subjectsRaw = readFileSync(path.join(contentDir, 'subjects.yml'), 'utf8')
const { levels, subjects } = yaml.load(subjectsRaw)
const subjectsWithFeatured = subjects.map((subject) => ({
  ...subject,
  featured: Array.isArray(subject.featured) ? subject.featured.map((item) => ({ type: item.type, id: item.id })) : [],
}))

const levelsTs = `// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
// Edit content/subjects.yml (or use the /admin CMS) and rebuild instead.
export type Level = {
  id: string
  title: string
  shortTitle: string
  description: string
}

export type FeaturedResource = {
  type: 'note' | 'blog' | 'quiz' | 'video'
  id: string
}

export type Subject = {
  id: string
  levelId: string
  title: string
  description: string
  color: string
  featured: FeaturedResource[]
}

export const levels: Level[] = ${jsonString(levels)}

export const subjects: Subject[] = ${jsonString(subjectsWithFeatured)}

export function getLevelById(levelId: string): Level | undefined {
  return levels.find((level) => level.id === levelId)
}

export function getSubjectById(subjectId: string): Subject | undefined {
  return subjects.find((subject) => subject.id === subjectId)
}

export function getSubjectsByLevel(levelId: string): Subject[] {
  return subjects.filter((subject) => subject.levelId === levelId)
}
`
writeFileSync(path.join(outDir, 'levels.ts'), levelsTs)

// --- guided curricula ---------------------------------------------------
const curriculumPath = path.join(contentDir, 'curriculum.yml')
const curriculumRaw = readFileSync(curriculumPath, 'utf8')
const { curricula = [] } = yaml.load(curriculumRaw) || {}

const curriculumTs = `// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
// Edit content/curriculum.yml (or use the /admin CMS) and rebuild instead.
export type CurriculumResourceType = 'note' | 'blog' | 'quiz' | 'video'

export type CurriculumChapterLink = {
  title: string
  url?: string
  unitId?: string
}

export type CurriculumLesson = {
  id: string
  title: string
  resourceType: CurriculumResourceType
  resourceId: string
  estimatedMinutes: number
  description: string
}

export type CurriculumUnit = {
  id: string
  order: number
  title: string
  summary: string
  estimatedMinutes: number
  outcomes: string[]
  lessons: CurriculumLesson[]
}

export type Curriculum = {
  id: string
  subjectId: string
  title: string
  description: string
  syllabusNote: string
  syllabusChapters: string
  syllabusChapterLinks: CurriculumChapterLink[]
  units: CurriculumUnit[]
}

export const curricula: Curriculum[] = ${jsonString(curricula)}

export function getCurriculumById(curriculumId: string): Curriculum | undefined {
  return curricula.find((curriculum) => curriculum.id === curriculumId)
}

export function getCurriculumBySubject(subjectId: string): Curriculum | undefined {
  return curricula.find((curriculum) => curriculum.subjectId === subjectId)
}
`
writeFileSync(path.join(outDir, 'curriculum.ts'), curriculumTs)

const FALLBACK_NOTE_DATE = '2026-07-19'

// --- notes, blogs, quizzes, videos ------------------------------------
const notes = readMarkdownFolder('notes').map((n) => ({
  id: n.id,
  subjectId: n.subjectId,
  title: n.title,
  summary: n.summary,
  toc: Array.isArray(n.toc) ? n.toc.filter((item) => typeof item === 'string') : [],
  date:
    typeof n.date === 'string'
      ? n.date
      : n.date
        ? new Date(n.date).toISOString().slice(0, 10)
        : FALLBACK_NOTE_DATE,
  image: n.image || '',
  imageAlt: n.imageAlt || '',
  slidesEnabled: n.slidesEnabled === true,
  slideControls: {
    mode: n.slideControls?.mode || 'auto',
    maxPoints: Number.isInteger(n.slideControls?.maxPoints) ? n.slideControls.maxPoints : 4,
    includeQuickCheck: n.slideControls?.includeQuickCheck !== false,
    sections: Array.isArray(n.slideControls?.sections) ? n.slideControls.sections : [],
    title: n.slideControls?.title || '',
  },
  visualBlocks: normalizeVisualBlocks(Array.isArray(n.visualBlocks) ? n.visualBlocks : []),
  body: n.body,
}))

const blogPosts = readMarkdownFolder('blogs').map((b) => ({
  id: b.id,
  subjectId: b.subjectId,
  title: b.title,
  date: typeof b.date === 'string' ? b.date : new Date(b.date).toISOString().slice(0, 10),
  excerpt: b.excerpt,
  image: b.image || '',
  body: b.body,
}))

const quizzes = readMarkdownFolder('quizzes').map((q) => ({
  id: q.id,
  subjectId: q.subjectId,
  title: q.title,
  topic: typeof q.topic === 'string' ? q.topic : '',
  setLabel: typeof q.setLabel === 'string' && q.setLabel.trim() ? q.setLabel : q.title,
  format: ['theory', 'numerical', 'mixed'].includes(q.format) ? q.format : 'mixed',
  questions: (q.questions || []).map((qq) => ({
    question: qq.question,
    options: qq.options,
    answerIndex: qq.answerIndex,
    explanation: qq.explanation,
  })),
}))

const practiceSets = readMarkdownFolder('practice-sets').map((p) => ({
  id: p.id,
  subjectId: p.subjectId,
  title: p.title,
  instructions: p.instructions || '',
  questions: (p.questions || []).map((pq) =>
    pq.type === 'writing'
      ? { type: 'writing', question: pq.question, points: Number.isFinite(pq.points) ? pq.points : 1 }
      : {
          type: 'numerical',
          question: pq.question,
          answer: pq.answer,
          tolerance: Number.isFinite(pq.tolerance) ? pq.tolerance : 0,
          points: Number.isFinite(pq.points) ? pq.points : 1,
        },
  ),
}))

const scheduledTests = readMarkdownFolder('scheduled-tests').filter((t) => t.published === true).map((t) => ({
  id: t.id,
  subjectId: t.subjectId,
  title: t.title,
  published: t.published === true,
  instructions: t.instructions || '',
  opensAt: t.opensAt || '',
  closesAt: t.closesAt || '',
  durationMinutes: Number.isFinite(t.durationMinutes) ? t.durationMinutes : 40,
  questions: (t.questions || []).map((question) => ({
    question: question.question,
    answer: question.answer,
    tolerance: Number.isFinite(question.tolerance) ? question.tolerance : 0,
    points: Number.isFinite(question.points) ? question.points : 1,
  })),
}))
const videos = readMarkdownFolder('videos').map((v) => ({
  id: v.id,
  subjectId: v.subjectId,
  title: v.title,
  topic: typeof v.topic === 'string' ? v.topic : '',
  youtubeId: v.youtubeId || '',
  description: v.description,
  transcript: v.transcript || '',
  keyTakeaways: v.keyTakeaways || [],
}))

const contentTs = `// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
// Edit files under /content (or use the /admin CMS) and rebuild instead.
export type NoteSlideMode = 'auto' | 'text' | 'bullets' | 'recap'

export type NoteSlideControls = {
  mode: NoteSlideMode
  maxPoints: number
  includeQuickCheck: boolean
  sections: string[]
  title: string
}

export type NoteVisualBlock = {
  type: 'formula' | 'table' | 'graph'
  title: string
  expression?: string
  explanation?: string
  columns?: string[]
  rows?: Array<Array<string | number>>
  asset?: string
  xLabel?: string
  yLabel?: string
  points?: Array<[number, number]>
}

export type Note = {
  id: string
  subjectId: string
  title: string
  summary: string
  toc: string[]
  date: string
  image: string
  imageAlt: string
  slidesEnabled: boolean
  slideControls: NoteSlideControls
  visualBlocks: NoteVisualBlock[]
  body: string
}

export type BlogPost = {
  id: string
  subjectId: string
  title: string
  date: string
  excerpt: string
  image: string
  body: string
}

export type QuizQuestion = {
  question: string
  options: string[]
  answerIndex: number
  explanation: string
}

export type Quiz = {
  id: string
  subjectId: string
  title: string
  topic: string
  setLabel: string
  format: 'theory' | 'numerical' | 'mixed'
  questions: QuizQuestion[]
}

export type ScheduledTestQuestion = {
  question: string
  answer: number
  tolerance: number
  points: number
}
export type ScheduledTest = {
  id: string
  subjectId: string
  title: string
  published: boolean
  instructions: string
  opensAt: string
  closesAt: string
  durationMinutes: number
  questions: ScheduledTestQuestion[]
}
export type Video = {
  id: string
  subjectId: string
  title: string
  topic: string
  youtubeId: string
  description: string
  transcript: string
  keyTakeaways: string[]
}

export type PracticeQuestion =
  | { type: 'numerical'; question: string; answer: number; tolerance: number; points: number }
  | { type: 'writing'; question: string; points: number }

export type PracticeSet = {
  id: string
  subjectId: string
  title: string
  instructions: string
  questions: PracticeQuestion[]
}

export const notes: Note[] = ${jsonString(notes)}

export const blogPosts: BlogPost[] = ${jsonString(blogPosts)}

export const quizzes: Quiz[] = ${jsonString(quizzes)}

export const videos: Video[] = ${jsonString(videos)}

export const practiceSets: PracticeSet[] = ${jsonString(practiceSets)}
export const scheduledTests: ScheduledTest[] = ${jsonString(scheduledTests)}
export function getNoteById(noteId: string): Note | undefined {
  return notes.find((note) => note.id === noteId)
}

export function getNotesBySubject(subjectId: string): Note[] {
  return notes.filter((n) => n.subjectId === subjectId)
}

export function getBlogPostById(blogId: string): BlogPost | undefined {
  return blogPosts.find((blog) => blog.id === blogId)
}

export function getBlogPostsBySubject(subjectId: string): BlogPost[] {
  return blogPosts.filter((b) => b.subjectId === subjectId)
}

export function getQuizById(quizId: string): Quiz | undefined {
  return quizzes.find((quiz) => quiz.id === quizId)
}

export function getQuizzesBySubject(subjectId: string): Quiz[] {
  return quizzes.filter((q) => q.subjectId === subjectId)
}

export function getPracticeSetById(practiceSetId: string): PracticeSet | undefined {
  return practiceSets.find((p) => p.id === practiceSetId)
}

export function getPracticeSetsBySubject(subjectId: string): PracticeSet[] {
  return practiceSets.filter((p) => p.subjectId === subjectId)
}
export function getScheduledTestById(scheduledTestId: string): ScheduledTest | undefined {
  return scheduledTests.find((test) => test.id === scheduledTestId)
}
export function getScheduledTestsBySubject(subjectId: string): ScheduledTest[] {
  return scheduledTests.filter((test) => test.subjectId === subjectId)
}
export function getVideoById(videoId: string): Video | undefined {
  return videos.find((video) => video.id === videoId)
}

export function getVideosBySubject(subjectId: string): Video[] {
  return videos.filter((v) => v.subjectId === subjectId)
}
`
writeFileSync(path.join(outDir, 'content.ts'), contentTs)

console.log(
  `Generated content: ${notes.length} notes, ${blogPosts.length} blog posts, ${quizzes.length} quizzes, ${videos.length} videos, ${subjectsWithFeatured.length} subjects, ${curricula.length} curricula.`,
)
