// Reads everything under /content (edited via the Decap CMS admin panel, or by hand)
// and turns it into the TypeScript data files the React app imports.
// Runs automatically before every `npm run dev` and `npm run build` (see package.json).
import { readFileSync, readdirSync, mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import matter from 'gray-matter'
import yaml from 'js-yaml'

const root = path.resolve(import.meta.dirname, '..')
const contentDir = path.join(root, 'content')
const outDir = path.join(root, 'src', 'data', 'generated')
mkdirSync(outDir, { recursive: true })

function readMarkdownFolder(folder) {
  const dir = path.join(contentDir, folder)
  let files = []
  try {
    files = readdirSync(dir).filter((f) => f.endsWith('.md'))
  } catch {
    return []
  }
  return files.map((file) => {
    const raw = readFileSync(path.join(dir, file), 'utf8')
    const { data, content } = matter(raw)
    const id = file.replace(/\.md$/, '')
    return { id, ...data, body: content.trim() }
  })
}

function jsonString(value) {
  return JSON.stringify(value, null, 2)
}

// --- subjects.yml (coursework levels + subjects) --------------------------------
const subjectsRaw = readFileSync(path.join(contentDir, 'subjects.yml'), 'utf8')
const { levels, subjects } = yaml.load(subjectsRaw)

const levelsTs = `// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
// Edit content/subjects.yml (or use the /admin CMS) and rebuild instead.
export type Level = {
  id: string
  title: string
  shortTitle: string
  description: string
}

export type Subject = {
  id: string
  levelId: string
  title: string
  description: string
  color: string
}

export const levels: Level[] = ${jsonString(levels)}

export const subjects: Subject[] = ${jsonString(subjects)}

export function getLevelById(levelId: string): Level | undefined {
  return levels.find((level) => level.id === levelId)
}

export function getSubjectById(subjectId: string): Subject | undefined {
  return subjects.find((subject) => subject.id === subjectId)
}

export function getSubjectsByLevel(levelId: string): Subject[] {
  return subjects.filter((subject) => subject.levelId === levelId)
}
`
writeFileSync(path.join(outDir, 'levels.ts'), levelsTs)

const FALLBACK_NOTE_DATE = '2026-07-19'

// --- notes, blogs, quizzes, videos ------------------------------------
const notes = readMarkdownFolder('notes').map((n) => ({
  id: n.id,
  subjectId: n.subjectId,
  title: n.title,
  summary: n.summary,
  date:
    typeof n.date === 'string'
      ? n.date
      : n.date
        ? new Date(n.date).toISOString().slice(0, 10)
        : FALLBACK_NOTE_DATE,
  image: n.image || '',
  body: n.body,
}))

const blogPosts = readMarkdownFolder('blogs').map((b) => ({
  id: b.id,
  subjectId: b.subjectId,
  title: b.title,
  date: typeof b.date === 'string' ? b.date : new Date(b.date).toISOString().slice(0, 10),
  excerpt: b.excerpt,
}))

const quizzes = readMarkdownFolder('quizzes').map((q) => ({
  id: q.id,
  subjectId: q.subjectId,
  title: q.title,
  questions: (q.questions || []).map((qq) => ({
    question: qq.question,
    options: qq.options,
    answerIndex: qq.answerIndex,
  })),
}))

const videos = readMarkdownFolder('videos').map((v) => ({
  id: v.id,
  subjectId: v.subjectId,
  title: v.title,
  youtubeId: v.youtubeId || '',
  description: v.description,
}))

const contentTs = `// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
// Edit files under /content (or use the /admin CMS) and rebuild instead.
export type Note = {
  id: string
  subjectId: string
  title: string
  summary: string
  date: string
  image: string
  body: string
}

export type BlogPost = {
  id: string
  subjectId: string
  title: string
  date: string
  excerpt: string
}

export type QuizQuestion = {
  question: string
  options: string[]
  answerIndex: number
}

export type Quiz = {
  id: string
  subjectId: string
  title: string
  questions: QuizQuestion[]
}

export type Video = {
  id: string
  subjectId: string
  title: string
  youtubeId: string
  description: string
}

export const notes: Note[] = ${jsonString(notes)}

export const blogPosts: BlogPost[] = ${jsonString(blogPosts)}

export const quizzes: Quiz[] = ${jsonString(quizzes)}

export const videos: Video[] = ${jsonString(videos)}

export function getNotesBySubject(subjectId: string): Note[] {
  return notes.filter((n) => n.subjectId === subjectId)
}

export function getBlogPostsBySubject(subjectId: string): BlogPost[] {
  return blogPosts.filter((b) => b.subjectId === subjectId)
}

export function getQuizzesBySubject(subjectId: string): Quiz[] {
  return quizzes.filter((q) => q.subjectId === subjectId)
}

export function getVideosBySubject(subjectId: string): Video[] {
  return videos.filter((v) => v.subjectId === subjectId)
}
`
writeFileSync(path.join(outDir, 'content.ts'), contentTs)

console.log(
  `Generated content: ${notes.length} notes, ${blogPosts.length} blog posts, ${quizzes.length} quizzes, ${videos.length} videos, ${subjects.length} subjects.`,
)
